/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PaintGUI;

import java.awt.Point;
import javax.swing.JColorChooser;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author alfa
 */
public class CircleFrame extends JFrame implements Node {

    /**
     * Creates new form circleFrame
     */
    private Circle circle;
    Node parent;
    
    public CircleFrame(Circle circle) {
        initComponents();
        this.setTitle("Circle");
        this.circle = circle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        circleXCor = new javax.swing.JLabel();
        circleYCor = new javax.swing.JLabel();
        circleRadius = new javax.swing.JLabel();
        circleXCorTextField = new javax.swing.JTextField();
        circleYCorTextField = new javax.swing.JTextField();
        circleHRadiusTextField = new javax.swing.JTextField();
        createCircleBtn = new javax.swing.JButton();
        fillColorBtn = new javax.swing.JButton();
        borderColorBtn = new javax.swing.JButton();
        circleRadius1 = new javax.swing.JLabel();
        circleVRadiusTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        circleXCor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        circleXCor.setText("X");

        circleYCor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        circleYCor.setText("Y");

        circleRadius.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        circleRadius.setText("Horizontal Radius");

        circleHRadiusTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circleHRadiusTextFieldActionPerformed(evt);
            }
        });

        createCircleBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createCircleBtn.setText("Create circle");
        createCircleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCircleBtnActionPerformed(evt);
            }
        });

        fillColorBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fillColorBtn.setText("Select fill color");
        fillColorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillColorBtnActionPerformed(evt);
            }
        });

        borderColorBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        borderColorBtn.setText("Select border color");
        borderColorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borderColorBtnActionPerformed(evt);
            }
        });

        circleRadius1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        circleRadius1.setText("Vertical Radius");

        circleVRadiusTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circleVRadiusTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(circleXCor)
                                    .addComponent(circleYCor)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(circleRadius1)
                                    .addComponent(circleRadius))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(circleVRadiusTextField)
                            .addComponent(circleYCorTextField)
                            .addComponent(circleHRadiusTextField)
                            .addComponent(circleXCorTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(createCircleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fillColorBtn))
                        .addGap(37, 37, 37)
                        .addComponent(borderColorBtn)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(circleXCor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(circleXCorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(circleYCor)
                    .addComponent(circleYCorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(circleRadius)
                    .addComponent(circleHRadiusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(circleRadius1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(circleVRadiusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fillColorBtn)
                    .addComponent(borderColorBtn))
                .addGap(18, 18, 18)
                .addComponent(createCircleBtn)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createCircleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCircleBtnActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(circleXCorTextField.getText());
        int y = Integer.parseInt(circleYCorTextField.getText());
        int horizontalRadius = Integer.parseInt(circleHRadiusTextField.getText());
        int verticalRadius = Integer.parseInt(circleVRadiusTextField.getText());
        circle.setVerticalRadius(verticalRadius);
        circle.setHorizontalRadius(horizontalRadius);
        circle.setPosition(new Point(x, y));
        this.setVisible(false);
        ((JFrame) getParentNode()).setVisible(true);
        

    }//GEN-LAST:event_createCircleBtnActionPerformed

    private void borderColorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borderColorBtnActionPerformed
        // TODO add your handling code here:
        Color borderColor = JColorChooser.showDialog(null, "Choose Border Color", Color.black);
        circle.setColor(borderColor);

    }//GEN-LAST:event_borderColorBtnActionPerformed

    private void fillColorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillColorBtnActionPerformed
        // TODO add your handling code here:
        Color fillColor = JColorChooser.showDialog(null, "Choose Fill Color", Color.black);
        circle.setFillColor(fillColor);
    }//GEN-LAST:event_fillColorBtnActionPerformed

    private void circleHRadiusTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circleHRadiusTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_circleHRadiusTextFieldActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        ((JFrame) getParentNode()).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void circleVRadiusTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circleVRadiusTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_circleVRadiusTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    /* public static void main(String args[]) {
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CircleFrame(null).setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borderColorBtn;
    private javax.swing.JTextField circleHRadiusTextField;
    private javax.swing.JLabel circleRadius;
    private javax.swing.JLabel circleRadius1;
    private javax.swing.JTextField circleVRadiusTextField;
    private javax.swing.JLabel circleXCor;
    private javax.swing.JTextField circleXCorTextField;
    private javax.swing.JLabel circleYCor;
    private javax.swing.JTextField circleYCorTextField;
    private javax.swing.JButton createCircleBtn;
    private javax.swing.JButton fillColorBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setParentNode(Node parent) {
        this.parent = parent;
    }
    
    @Override
    public Node getParentNode() {
        return parent;
    }
}
