/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PaintGUI;

import java.awt.Point;
import javax.swing.JColorChooser;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author alfa
 */
public class SquareFrame extends JFrame implements Node {

    /**
     * Creates new form RectFrame
     */
    private Rectangle square;
    Node parent;

    public SquareFrame(Rectangle square) {
        initComponents();
        this.setTitle("Square");
        this.square = square;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        squareXCorFieldText = new javax.swing.JTextField();
        squareYCorFieldText = new javax.swing.JTextField();
        squareSideLength = new javax.swing.JTextField();
        fillColorBtn = new javax.swing.JButton();
        borderColorBtn = new javax.swing.JButton();
        createRectBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("X");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Y");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Side's Length");

        squareXCorFieldText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareXCorFieldTextActionPerformed(evt);
            }
        });

        squareSideLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareSideLengthActionPerformed(evt);
            }
        });

        fillColorBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fillColorBtn.setText("Select fill color");
        fillColorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillColorBtnActionPerformed(evt);
            }
        });

        borderColorBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        borderColorBtn.setText("Select border color");
        borderColorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borderColorBtnActionPerformed(evt);
            }
        });

        createRectBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createRectBtn.setText("Create square");
        createRectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createRectBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(fillColorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(squareXCorFieldText)
                            .addComponent(squareYCorFieldText)
                            .addComponent(squareSideLength))
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(borderColorBtn)
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(squareXCorFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(squareYCorFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(squareSideLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borderColorBtn)
                    .addComponent(fillColorBtn))
                .addGap(18, 18, 18)
                .addComponent(createRectBtn)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillColorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillColorBtnActionPerformed
        // TODO add your handling code here: 
        Color fillColor = JColorChooser.showDialog(null, "Choose Fill Color", Color.black);
        square.setColor(fillColor);
    }//GEN-LAST:event_fillColorBtnActionPerformed

    private void createRectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRectBtnActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(squareXCorFieldText.getText());
        int y = Integer.parseInt(squareYCorFieldText.getText());
        int sideLength = Integer.parseInt(squareSideLength.getText());
        square.setWidth(sideLength);
        square.setHeight(sideLength);
        square.setPosition(new Point(x, y));
        this.setVisible(false);
        ((JFrame) getParentNode()).setVisible(true);


    }//GEN-LAST:event_createRectBtnActionPerformed

    private void squareSideLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareSideLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_squareSideLengthActionPerformed

    private void squareXCorFieldTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareXCorFieldTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_squareXCorFieldTextActionPerformed

    private void borderColorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borderColorBtnActionPerformed
        // TODO add your handling code here:
        Color borderColor = JColorChooser.showDialog(null, "Choose Border Color", Color.black);
        square.setColor(borderColor);
    }//GEN-LAST:event_borderColorBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        ((JFrame) getParentNode()).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
  /*  public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SquareFrame(null).setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borderColorBtn;
    private javax.swing.JButton createRectBtn;
    private javax.swing.JButton fillColorBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField squareSideLength;
    private javax.swing.JTextField squareXCorFieldText;
    private javax.swing.JTextField squareYCorFieldText;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setParentNode(Node parent) {
        this.parent = parent;
    }

    @Override
    public Node getParentNode() {
        return parent;
    }
}
